services:
  gate:
    build:
      context: ./services
      dockerfile: Gate.Dockerfile
    ports:
      - "8001:8000"
  light:
    build:
      context: ./services
      dockerfile: Light.Dockerfile
    ports:
      - "8002:8000"
  simulate_sensors:
    build:
      context: ./simulate_sensors
      dockerfile: Dockerfile
    environment:
      - "OTLP_ENPOINT=${OTLP_ENPOINT}"
      - "METRICS_INTERVAL=${METRICS_INTERVAL}"
      - "NATS_URL=${NATS_URL}"