services:
  services:
    build:
      context: ./services
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - "OTLP_ENDPOINT=${OTLP_ENDPOINT}"
      - "METRICS_INTERVAL=${METRICS_INTERVAL}"
  simulate_sensors:
    build:
      context: ./simulate_sensors
      dockerfile: Dockerfile
    environment:
      - "OTLP_ENDPOINT=${OTLP_ENDPOINT}"
      - "START_INTERVAL_IN_SECONDS=${START_INTERVAL_IN_SECONDS}"
      - "END_INTERVAL_IN_SECONDS=${END_INTERVAL_IN_SECONDS}"
      - "METRICS_INTERVAL=${METRICS_INTERVAL}"
      - "NATS_URL=${NATS_URL}"