services:
  quarkus-app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
      - "5005:5005"
    networks:
      - quarkus-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  quarkus-network:
    driver: bridge