- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: true
  become: true

- name: Ensure Docker is started and enabled
  service:
    name: docker
    state: started
    enabled: true
  become: true

- name: Run cloud services in Docker
  docker_container:
    name: service-cloud
    image: "lellson/surveillance-cloud-service:develop"
    state: started
    recreate: true
    force_kill: true
    pull: true
    ports:
      - "8002:8002"
    env:
      PROTO: "{{ hostvars[inventory_hostname]['PROTO'] }}"
  become: true
  register: service_cloud_container
