- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: true
  become: true

- name: Ensure Docker is started and enabled
  service:
    name: docker
    state: started
    enabled: true
  become: true

- name: Run Sonataflow
  docker_container:
    name: sonataflow
    image: "lellson/swf-sonataflow-surveillance-system:{{ hostvars[inventory_hostname]['IMAGE_TAG'] }}"
    state: started
    recreate: true
    force_kill: true
    pull: true
    ports:
      - "8080:8080"
  become: true
  register: sonataflow_container
