- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: true
  become: true

- name: Ensure Docker is started and enabled
  service:
    name: docker
    state: started
    enabled: true
  become: true

- name: Run Mock-Camera service in Docker
  docker_container:
    name: service-camera
    image: "lellson/cirrina-examples-mock-camera:develop"
    state: started
    recreate: true
    force_kill: true
    pull: true
    ports:
      - "8001:8001"
    env:
      PROTO: "{{ hostvars[inventory_hostname]['PROTO'] }}"
  become: true
  register: service_camera_container

- name: Run Object-Detection service in Docker
  docker_container:
    name: service-object-detection
    image: "lellson/cirrina-examples-object-detection:develop"
    state: started
    recreate: true
    force_kill: true
    pull: true
    ports:
      - "8000:8000"
    env:
      PROTO: "{{ hostvars[inventory_hostname]['PROTO'] }}"
  become: true
  register: service_object_detection_container
